---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: triggers-demo

resources:
  - serviceaccount.yaml
  # ROLES
  - app-deployer.yaml
  - tekton-triggers-admin.yaml
  - tekton-triggers-webhook.yaml
  #ROLE Bindings
  - role-bindings.yaml
