apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
spec:
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
        - name: greeter
          image: quay.io/rhdevelopers/tekton-tutorial-greeter:springboot
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 8080
