apiVersion: v1
kind: Secret
metadata:
  name: private-git-secret
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  # cat ~/.ssh/<your-git-private-key> | base64
  ssh-privatekey: <base64 encoded>
  # cat ~/.ssh/known_hosts | base64
  known_hosts: <base64 encoded>
