apiVersion: v1
kind: Secret
metadata:
  name: remote-registry-secret
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  # update to match your username
  username: <username>
  # update this to match your user password
  password: <password>
