apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helloworld-app-build
spec:
  description: >-
    The Pipline to build and push the Java App from https://github.com/redhat-developer-demos/tekton-helloworld to an external container registry
  params:
    - name: image-name #<.>
      description: The fully qualified image name e.g example.com/tekton-tutorial/helloworld
      default: quay.io/rhdevelopers/tekton-helloworld
    - name: github-repo-url
      description: The GitHub Repo of the Java Application
      default: https://github.com/redhat-developer-demos/tekton-helloworld
    - name: github-repo-revision
      description: The GitHub revision to use
      default: master
  workspaces:
    - name: source #<.>
    - name: maven-settings #<.>
  tasks:
    - name: build-java-app
      taskRef:
        name: maven
      params:
        - name: GOALS
          value: ['-B', '-DskipTests', 'clean', 'package']
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: source
    - name: build-java-app-image
      taskRef:
        name: buildah
      runAfter:
        - build-java-app
      params:
        - name: IMAGE
          value: '$(params.image-name)'
      workspaces:
        - name: source
          workspace: source
