apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: secretworld-app-clone
spec:
  description: >-
    The pipeline to clone from private GitHub repo and list the directory
  params:
    - name: private-github-repo-url
      description: The private GitHub Repo
    - name: github-repo-revision
      description: The GitHub revision to use
      default: master
  workspaces:
    - name: source
  tasks:
    - name: clone-sources
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.private-github-repo-url)
        - name: revision
          value: $(params.github-repo-revision)
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: source
    - name: list-cloned-repo
      taskRef:
        name: list-directory
      runAfter:
        - clone-sources
      workspaces:
        - name: directory
          workspace: source
